version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "Installing terraform"
      - apt-get update -y
      - apt-get install -y wget unzip

      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

      - chmod +x bin/build.sh bin/postbuild.sh

  pre_build:
    commands:
      - echo "Build ${BUILD_NUMBER}"

  build:
    commands:
      - ./bin/build.sh

  post_build:
    commands:
      - ./bin/postbuild.sh

artifacts:
  files:
    - build/image-metadata.env